webtalk_init -webtalk_dir C:/Users/Kushagra Sharma/Downloads/Digital Systems/Image_Detection_SIMULATION/Image_Detection_SIMULATION.sim/sim_1/behav/xsim/xsim.dir/final_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Nov 14 18:48:04 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5f2bd2f5-1f77-49c7-9baf-c42e4795bb09" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5767837f831f4ae4b23c988727d68894" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "85" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "5" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "182 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "20 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "222" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "9" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.31_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "68324_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2038472714 -regid "" -xml C:/Users/Kushagra Sharma/Downloads/Digital Systems/Image_Detection_SIMULATION/Image_Detection_SIMULATION.sim/sim_1/behav/xsim/xsim.dir/final_test_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Kushagra Sharma/Downloads/Digital Systems/Image_Detection_SIMULATION/Image_Detection_SIMULATION.sim/sim_1/behav/xsim/xsim.dir/final_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Kushagra Sharma/Downloads/Digital Systems/Image_Detection_SIMULATION/Image_Detection_SIMULATION.sim/sim_1/behav/xsim/xsim.dir/final_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
